### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by luyanda** [generate/generate-travis#3]
I'm not getting what am suppose to get, this is the output after running gen travis
n - (C) 1997 by Tom Sailer HB9JNX/AE4WA
gen
Generates test signals
(C) 1997 by Thomas Sailer HB9JNX/AE4WA
  -t <type>  : input file type (any other type than raw requires sox)
  -a <ampl>  : amplitude
  -d <str>   : encode DTMF string
  -z <str>   : encode ZVEI string
  -c <str>   : encode CCIR string
  -s <freq>  : encode sine
  -p <text>  : encode hdlc packet

**Comment by doowb** [comment]
This looks like there's another program called `gen` on your system. Try using `generate` instead of `gen` to see if there's a conflict.
